# NOTE: use `nix develop .` to ensure you are using the latest xplr code for demo
Output demo.gif

Set FontSize 30
Set Width 1200
Set Height 800
Set TypingSpeed 0.2
Set Padding 1

Type@50ms "curl https://pokeapi.co/api/v2/pokemon/155 | xplr"
Enter
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Down
Sleep 1s
Tab
Sleep 1s
Down
Sleep 1s
Tab
Sleep 1s
Type "3"
Sleep 1s
Down
Sleep 1s
Type@500ms "/flame"
Sleep 1s
Enter
Sleep 1s
Type n
Sleep 1s
Type n
Sleep 1s
Type n
Sleep 1s
Type gg
Sleep 2s
