# NOTE: use `nix develop .` to ensure you are using the latest wndr code for demo
Output demo.gif

Set FontSize 20
Set Width 1200
Set Height 600
Set TypingSpeed 0.2
Set Padding 1

Type@50ms "curl https://pokeapi.co/api/v2/pokemon/155 | wndr"
Enter
Sleep 0.5s
Down
Sleep 0.5s
Down
Sleep 0.5s
Down
Sleep 0.5s
Tab
Sleep 0.5s
Down
Sleep 0.5s
Tab
Sleep 0.5s
Type "3"
Sleep 0.5s
Down
Sleep 0.5s
Type@200ms "/flame"
Sleep 0.5s
Enter
Sleep 0.5s
Type n
Sleep 0.5s
Type n
Sleep 0.5s
Type n
Sleep 0.5s
Type gg
Sleep 2s
