# NOTE: use `nix develop .` to ensure you are using the latest wndr code for demo
Output diff.gif

Set FontSize 20
Set Width 1200
Set Height 600
Set Padding 1

Hide
Set TypingSpeed 0
Type "wndr diff -f <(curl -sS https://pokeapi.co/api/v2/pokemon/155) -f <(curl -sS https://pokeapi.co/api/v2/pokemon/156) -f <(curl -sS https://pokeapi.co/api/v2/pokemon/157) -k _cynd -k _quil -k _typh"
Show

Set TypingSpeed 0.2
Sleep 1s
Enter
Sleep 0.5s
Type "G"
Enter
Sleep 0.5s
Tab
Sleep 0.5s
Up
Sleep 0.5s
Tab
Sleep 0.5s
Down
Sleep 0.5s
Tab
Sleep 0.5s
Down
Sleep 0.5s
Tab
Sleep 0.5s
Down
Sleep 0.5s
Tab
Sleep 0.5s
Type@200ms "/items"
Sleep 0.5s
Enter
Sleep 0.5s
Down 2
Sleep 0.5s
Type ">"
Sleep 0.5s
Type gg
Sleep 2s
