name: Go Test

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  go-fmt:
    runs-on: ubuntu-slim
    continue-on-error: true
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: gofmt
        run: |
          OUTPUT=$(gofmt -l -s .)
          if [ -n "$OUTPUT" ]; then
            echo "The following files are not formatted correctly:"
            echo "$OUTPUT"
            exit 1
          fi

  go-tests:
    runs-on: ubuntu-slim
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  govulncheck:
    runs-on: ubuntu-slim
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.24
